name: Copy Index from Chroma to ChromaDocTest

on:
  push:
    branches: [ main ]

jobs:
  copy-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve index.ts as artifact
        run: |
          mkdir docs
          cp clients/js/src/index.ts docs/
        
      - name: Upload index.ts artifact
        uses: actions/upload-artifact@v2
        with:
          name: index.ts
          path: docs/index.ts
          
      - name: Checkout code of ChromaDocTest repo
        uses: actions/checkout@v2
        with:
          repository: naynaly10/chromaDocTest
          token: ${{ secrets.SECRET_TOKEN }}
          
      - name: Download index.ts artifact
        uses: actions/download-artifact@v2
        with:
          name: index.ts
          path: docs/
          
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          commit-message: "Copy index.ts from Chroma to ChromaDocTest"
          branch: main
          base: main
          title: "Copy index.ts from Chroma to ChromaDocTest"
          body: "This PR copies the `index.ts` file from the `naynaly10/chroma` repository to the `naynaly10/chromaDocTest` repository."
          labels: "auto-generated"
